name: 'Slack Notify'
description: 'Notify Slack of releases'
runs:
  using: 'node20'
  main: 'index.js'
inputs:
  repo-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  token:
    description: Slack access token
    required: true
  channel:
    description: Slack channel
    required: false
    default: '#infra-webhooks'
  tag-prefix:
    description: Prefix for release tag
    required: false
    default: ''
  template:
    description: Message template
    required: false
    default: 'released to *<%= environment %>*'
